### ISSUE TITLE
Runtime compilation issues on Ubuntu22.04

### ISSUE THREAD

**Issue by zhao-han** [bytedance/byteir#15]
Hi, I got two issues when trying to compile runtime on Ubuntu22.04:

1. log:
```
/work/dev/byteir/byteir/runtime/include/brt/core/context/execution_frame.h:128:14: error: ‘unique_lock’ is not a member of ‘std’
  128 |         std::unique_lock<std::shared_mutex> lock_write(mutex);
```
Adding `#include <mutex>` for `/runtime/include/brt/core/context/execution_frame.h` can fix this issue.

2. log:
```
/work/dev/byteir/byteir/runtime/include/brt/core/framework/op_kernel_info.h:92:20:   required from here
/usr/include/c++/11/bits/stl_pair.h:217:11: error: ‘std::pair<_T1, _T2>::first’ has incomplete type
```

Adding `#include <string>` to `/runtime/include/brt/core/framework/op_kernel_info.h` can fix this issue.

**Comment by liwenchangbdbz** [comment]
Thanks for pointing it out. We will fix it soon.

**Comment by liwenchangbdbz** [comment]
We just fixed the issue. Thanks for contribution.
