### ISSUE TITLE
[BUG] mhlo.batch_norm_inference  not support

### ISSUE THREAD

**Issue by lyffly** [bytedance/byteir#269]
err message:
`Traceback (most recent call last):
  File "compile_resnet18.py", line 6, in <module>
    compile("./resnet18.mlirbc", "./resnet18.cuda.mlir", entry_func="forward", target="cuda", verbose=True)
  File "/usr/local/lib/python3.8/dist-packages/byteir/compile.py", line 220, in compile
    compile_cuda(module, output_file_path, entry_func, verbose)
  File "/usr/local/lib/python3.8/dist-packages/byteir/compile.py", line 40, in compile_cuda
    PassManager.parse("builtin.module(byre-tensor-opt{{append-arg-types {}}})".format(entry_func_str)).run(module.operation)
byteir._mlir_libs.MLIRError: Failure while executing pass pipeline:
error: "-":111:12: failed to legalize operation 'mhlo.batch_norm_inference' that was explicitly marked illegal
 note: "-":111:12: see current operation: %205 = "mhlo.batch_norm_inference"(%204, %191, %189, %195, %193) {epsilon = 9.99999974E-6 : f32, feature_index = 1 : i64} : (tensor<1x64x112x112xf32>, tensor<64xf32>, tensor<64xf32>, tensor<64xf32>, tensor<64xf32>) -> tensor<1x64x112x112xf32>`

hello, when use byteir compile resnet18, error show not support   mhlo.batch_norm_inference , is it supported or I use wrong version , thank you ?

**Comment by qingyunqu** [comment]
Hi, sorry for the late reply. I have released ByteIR 1.8.4.0. You could try the latest version.
