### ISSUE TITLE
[Torch-frontend]Fail to use torch-frontend

### ISSUE THREAD

**Issue by FengJungle** [bytedance/byteir#459]
**Describe the bug**
build torch-frontend as scripts/build.sh, run example/inference/infer_resnet.py failed:
'PYTHONPATH=./build/python_packages/:build/torch_mlir_build/python_packages/torch_mlir python3 examples/inference/infer_resnet.py'

**ModuleNotFoundError: No module named 'torch_mlir._mlir_libs._jit_ir_importer'**

**To Reproduce**
1. clone byteir repo
2. cd byteir/frontend/torch-frontend
3. bash script/build.sh
4. PYTHONPATH=./build/python_packages/:build/torch_mlir_build/python_packages/torch_mlir python3 examples/inference/infer_resnet.py

**Expected behavior**
run over without error, and output resnet18 stablehlo.mlir file.

**Stack trace/logs**
/root/miniconda3/envs/torch-mlir/lib/python3.11/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/root/miniconda3/envs/torch-mlir/lib/python3.11/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/workspace/byteir/frontends/torch-frontend/examples/inference/infer_resnet.py", line 16, in <module>
    module = compile(model, data, "stablehlo")#, use_tracing=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/byteir/frontends/torch-frontend/build/python_packages/torch_frontend/compile.py", line 174, in compile
    from torch_mlir import torchscript
  File "/workspace/byteir/frontends/torch-frontend/build/torch_mlir_build/python_packages/torch_mlir/torch_mlir/torchscript.py", line 25, in <module>
    from torch_mlir.jit_ir_importer import ClassAnnotator, ImportOptions, ModuleBuilder
  File "/workspace/byteir/frontends/torch-frontend/build/torch_mlir_build/python_packages/torch_mlir/torch_mlir/jit_ir_importer/__init__.py", line 14, in <module>
    from .._mlir_libs._jit_ir_importer import *
ModuleNotFoundError: No module named 'torch_mlir._mlir_libs._jit_ir_importer'

**Environment**

**Proposed fix**
If you have a proposal for how to fix the issue state it here or link to a PR.

**Additional context**

**Comment by qingyunqu** [comment]
The failure should be because jit ir imporetr was not enabled during compilation.
You can use `torch-frontend` which I released to verify it, like: https://github.com/bytedance/byteir/releases/tag/v1.9.1.0.
Note: `torch-frontend` I released must be used with `torch==2.1.0`

**Comment by FengJungle** [comment]
> The failure should be because jit ir imporetr was not enabled during compilation. You can use `torch-frontend` which I released to verify it, like: https://github.com/bytedance/byteir/releases/tag/v1.9.1.0. Unzip the tar you will get it. Note: `torch-frontend` I released must be used with `torch==2.1.0`

@qingyunqu thanks for your reply!
when I use 

PYTHONPATH=./build/python_packages/:build/torch_mlir_build/python_packages/torch_mlir/**torch_mlir**

It works!

**Comment by qingyunqu** [comment]
@FengJungle Hi, I fix this bug in https://github.com/bytedance/byteir/pull/475.  
The key is to build `TorchMLIRJITIRImporterPybind` target when building `torch-mlir`.
