### ISSUE TITLE
[QUESTION] Could you please add details on how to build llvm-project for onnx-frontend?

### ISSUE THREAD

**Issue by FengJungle** [bytedance/byteir#467]
**Your question**
Could you please add details on how to build llvm-project for onnx-frontend? Currently, the README.md in onnx-frontend only said 
“First, build MLIR (llvm-project commit b2cdf3cc4c08729d0ff582d55e40793a20bbcdcc) with cmake option -DLLVM_ENABLE_RTTI=ON”.

I followed and built llvm-project. Then to build onnx-frontend, it said: llc/opt/llvm-dis not exist. So how to build llvm-project?

**Comment by Connor-XY** [comment]
Hi @FengJungle, I've already updated the readme of onnx-frontend and included detailed instructions for building llvm-project (see this [MR](https://github.com/bytedance/byteir/pull/468)). Would you please follow the instructions in the updated version and try to build llvm-project again? Sorry for any inconvenience.

**Comment by FengJungle** [comment]
> Hi @FengJungle, I've already updated the readme of onnx-frontend and included detailed instructions for building llvm-project (see this [MR](https://github.com/bytedance/byteir/pull/468)). Would you please follow the instructions in the updated version and try to build llvm-project again? Sorry for any inconvenience.

@Connor-XY @liwenchangbdbz It works! Many thanks for your work!
