### ISSUE TITLE
How to run onnx-frontend unit test? 

### ISSUE THREAD

**Issue by FengJungle** [bytedance/byteir#484]
https://github.com/bytedance/byteir/blob/42c5e7bdf6e34cea1d5e21d13a290740b3074f97/frontends/onnx-frontend/test/base.py#L11C1-L11C47

There are many unit test cases in onnx-frontend/tests/, how to run them?

**Comment by Connor-XY** [comment]
The tests use the Interpreter of stablehlo to interpret the stablehlo dialect generated, and compare the result with that from onnxruntime. Currently, mhlo_tools is not open-sourced yet. However, it is possible to build your own interpreter or use the one from stablehlo [here](https://openxla.org/stablehlo/reference). There are some tests [here](https://github.com/openxla/stablehlo/blob/main/stablehlo/tests/interpret/) that you can refer to. You can feed the same input to both onnxruntime and the stablehlo mlir generated from onnx-frontend, and see if their outputs match.

**Comment by FengJungle** [comment]
@Connor-XY Thanks for your reply!
I've tried stablehlo interpreter. Running stablehlo interpreter is really too slow......especially for matmul. Anyway, thank you all the same !
