### ISSUE TITLE
how to define a custom op in torch mlir

### ISSUE THREAD

**Issue by shirya0928** [bytedance/byteir#53]
Can you give an example demo of convert a fx graph to torch mlir? the fx graph include at least one custom op like "dynamic_partition" "dynamic_stitch" "dynamic_mask_stitch".

**Comment by zhekunz2** [comment]
Hi @shirya0928, thanks for bring this up!
We use "dynamic_partition" "dynamic_stitch" "dynamic_mask_stitch" when converting torchscript to torch mlir for now. For FX graph (dynamo -> torch-mlir), we have an example of torch custom op internally right now. I can point you the example and provide more context to you once we sync with our internal repo (in 1-2 days).

**Comment by zhekunz2** [comment]
We just released flash-attention-2 integration, and you can take a look as an example. 
custom op definition: 
https://github.com/bytedance/byteir/blob/main/frontends/torch-frontend/torch-frontend/python/torch_frontend/flash_attn_op.py#L129
torch mlir extra library: 
https://github.com/bytedance/byteir/blob/main/frontends/torch-frontend/torch-frontend/python/torch_frontend/convert_to_mhlo.py#L63
e2e test:
https://github.com/bytedance/byteir/blob/main/tests/numerical_test/torch_dynamo_e2e_testing/test_suite/test_flash_attn.py
