### ISSUE TITLE
[Test]: How do I get test cases for pass?

### ISSUE THREAD

**Issue by MbjYjbpivj** [bytedance/byteir#84]
Is there any way to get test cases for passes? Like "insert-detensorize-transform" pass.

**Comment by liwenchangbdbz** [comment]
Let me make sure I understand your need correctly.
The pass "insert-detensorize-transform" insert a transform op, structure.detensorize, but not perform the detensorize transformation  yet. 
The performing transform op will happen at "transform-dialect-interpreter". 
does your question refer to a test for a) performing detensorize transformation or b) just inserting transform op?

**Comment by liwenchangbdbz** [comment]
https://github.com/bytedance/byteir/pull/86
You can find the test in this PR.
